# Generated by Django 3.2.7 on 2021-09-09 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetailes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=120)),
                ('book_color', models.CharField(choices=[('book', 'white'), ('book', 'black')], max_length=120)),
                ('book_price', models.IntegerField()),
                ('book_title', models.CharField(max_length=120)),
                ('book_cost', models.IntegerField()),
                ('book_year', models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], max_length=100)),
                ('book_address', models.TextField()),
            ],
        ),
    ]
