# Generated by Django 3.2.7 on 2021-09-09 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genaricapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdetailes',
            old_name='book_cost',
            new_name='book_cost_finall',
        ),
    ]
